### ISSUE TITLE
tlf_bandmap uses fixed working directory

### ISSUE THREAD

**Issue by dl1jbe** [zcsahok/tlf_bandmap#1]
TLF as well as tlf_bandmap have to be started from home directory.

**Comment by zcsahok** [comment]
Yes, going to fix it. Thanks for reporting!

**Comment by zcsahok** [comment]
Fixed by 1704ce8 / 26e1d79
- added all bands (as per Tlf)
- _c/s/m_ option selects mode
- _w_ enables WARC bands; not needed when a WARC band is specified at start
- _d_ specifies working directory
- left/right switches band as in Tlf
- band switching remembers selected frequency range

**Comment by dl1jbe** [comment]
Well done.
